In [5]:
#libraries needed for script
import numpy as np
import pandas as pd
import pickle

In [7]:
#Remember to download the pickle file from this url --> 'INCLUDE FINAL URL HERE' 
#Save it to your local directory where you are running jupyter
df = pd.read_pickle('volAllFrames_Final.pkl.xz', compression='xz')
display(df.head())

,Filename,filetype,TimeStamp,segment,faceId,interocularDistance,Italk,Wtalk,silence,Wthink,...,root,gaze_0_x,gaze_0_y,gaze_0_z,gaze_1_x,gaze_1_y,gaze_1_z,gaze_angle_x,gaze_angle_y,predictedNumber_abdullah
0,2018-02-17_14-33-35-477-I-T-Ikingferry.csv,I-T,0.000,XX,0.0,111.6357,0,0,1,0,...,2018-02-17_14-33-35-477,0.169862,0.147179,-0.974415,-0.011821,0.203883,-0.978924,0.081,0.178,NaN
1,2018-02-17_14-33-35-477-I-T-Ikingferry.csv,I-T,0.067,XX,0.0,110.7060,0,0,1,0,...,2018-02-17_14-33-35-477,0.197858,0.155651,-0.967794,-0.076232,0.253722,-0.964268,0.063,0.209,NaN
2,2018-02-17_14-33-35-477-I-T-Ikingferry.csv,I-T,0.133,XX,0.0,111.3205,0,0,1,0,...,2018-02-17_14-33-35-477,0.195065,0.156115,-0.968286,-0.076072,0.254627,-0.964043,0.062,0.209,NaN
3,2018-02-17_14-33-35-477-I-T-Ikingferry.csv,I-T,0.200,XX,0.0,112.7393,0,0,1,0,...,2018-02-17_14-33-35-477,0.146418,0.140717,-0.979163,-0.059441,0.255373,-0.965014,0.045,0.201,NaN
4,2018-02-17_14-33-35-477-I-T-Ikingferry.csv,I-T,0.267,XX,0.0,115.2399,0,0,1,0,...,2018-02-17_14-33-35-477,0.146454,0.142378,-0.978918,-0.059855,0.263490,-0.962803,0.045,0.206,NaN

In [8]:
#Testing out to see if new pickle works
df_OpenFace = pd.read_pickle('features.pkl.xz', compression='xz')
display(df_OpenFace.head())

,Filename,TimeStamp,pose_Tx,pose_Ty,pose_Tz,pose_Rx,pose_Ry,pose_Rz,AU01_r,AU02_r,...,AU45_c,participant_id,gaze_0_x,gaze_0_y,gaze_0_z,gaze_1_x,gaze_1_y,gaze_1_z,gaze_angle_x,gaze_angle_y
0,2018-02-17_14-33-35-477-I-T-Ikingferry.csv,0.000,17.8,34.5,407.6,0.088,-0.042,-0.069,0.80,0.0,...,0.0,1001,0.169862,0.147179,-0.974415,-0.011821,0.203883,-0.978924,0.081,0.178
1,2018-02-17_14-33-35-477-I-T-Ikingferry.csv,0.067,18.0,34.1,409.5,0.089,-0.055,-0.082,0.32,0.0,...,0.0,1001,0.197858,0.155651,-0.967794,-0.076232,0.253722,-0.964268,0.063,0.209
2,2018-02-17_14-33-35-477-I-T-Ikingferry.csv,0.133,18.1,34.0,409.7,0.089,-0.053,-0.086,0.07,0.0,...,0.0,1001,0.195065,0.156115,-0.968286,-0.076072,0.254627,-0.964043,0.062,0.209
3,2018-02-17_14-33-35-477-I-T-Ikingferry.csv,0.200,17.8,33.8,407.5,0.092,-0.058,-0.092,0.05,0.0,...,0.0,1001,0.146418,0.140717,-0.979163,-0.059441,0.255373,-0.965014,0.045,0.201
4,2018-02-17_14-33-35-477-I-T-Ikingferry.csv,0.267,16.8,33.8,405.9,0.101,-0.053,-0.093,0.09,0.0,...,0.0,1001,0.146454,0.142378,-0.978918,-0.059855,0.263490,-0.962803,0.045,0.206